create database CSDL_TRACUUTHONGTIN
use CSDL_TRACUUTHONGTIN
create table MON_HOC
(
	CAUHOI nvarchar(500),
	TRALOI nvarchar(MAX),
	HINHANH varchar(MAX),
)
create table GIANG_VIEN
(
	CAUHOI nvarchar(500),
	TRALOI nvarchar(MAX),
	HINHANH varchar(MAX),
)
create table THONGTIN_QUYCHE
(
	CAUHOI nvarchar(500),
	TRALOI nvarchar(MAX),
	HINHANH varchar(MAX),
)

--Insert MON_HOC
insert into MON_HOC values (N'Lập trình Hướng đối tượng?',N'Tên tiếng Anh là Object Oriented Programming. '+char(10)+N'Số tín chỉ: 4. '+char(10)+N'Môn học này trình bày về lập trình hướng đối tượng với ngôn ngữ C++. '+char(10)+N'Chương trình môn học gồm 2 phần cơ bản được chia thành 9 chương. '+char(10)+N'Phần 1 bao gồm 4 chương đầu tiên giới thiệu về lập trình C++ cơ bản như: Kiểu dữ liệu, luồng điều khiển, hàm, tham số, chồng hàm, mảng, con trỏ và mảng động. '+char(10)+N'Phần 2 gồm 5 chương tiếp theo trình bài về lập trình hướng đối tượng như: cấu trúc, lớp, constructor, destructor, overload, friend, reference, kế thừa, đa hàm, hàm ảo.',null)
insert into MON_HOC values (N'Nhập môn phát triển Game',N'Tên tiếng Anh: Introduction to Game development.'+char(10)+N'Số tín chỉ: 3.'+char(10)+N'Tóm tắt nội dung:Môn học giới thiệu cho Sinh viên những khái niệm, thông tin cơ bản trong ngành game và đi sâu vào kỹ thuật lập trình DirectX để xây dựng các game 2D đơn giản như Tetris, Battle City, Mario, Contras...'+char(10)+N'Chương 1 giới thiệu tổng quan về ngành game.'+char(10)+N'Chương 2 giới thiệu về kỹ thuật lập trình Windows dùng C++ và Windows SDK.'+char(10)+N'Chương 3 giới thiệu kỹ thuật làm chuyển động và kỹ thuật lập trình DirectX cơ bản.'+char(10)+N'Chương 4 cung cấp kỹ thuật làm việc với Sprite và xử lý thiết bị nhập.'+char(10)+N'Chương 5 thảo luận về các kỹ thuật hỗ trợ khác như phép biến đổi, lập trình DirectSound, hiển thị chữ ...'+char(10)+N'Chương 6 bàn luận về Game Engine và cách xây dựng một game engine đơn giản.','csdl\\IMAGES\\MON_HOC\\nmptg.jpg')
insert into MON_HOC values (N'Ngôn ngữ lập trình Java',N'Tên tiếng Anh: Java Programming Language.'+char(10)+N'Số tín chỉ: 4 '+char(10)+N'Tóm tắt nội dung: Môn học cung cấp các kiến thức cơ bản ngôn ngữ Java, lập trình giao diện với AWT - Abstract Window Toolkit, lập trình đa luồng - Multithreading, lập trình cở sở dữ liệu. Môn học cũng cấp các kiến thức giúp sinh viên làm quen với các công cụ sử dụng trong ngôn ngữ lập trình Java.',null)
insert into MON_HOC values (N'Giới thiệu ngành',N'Tên tiếng Anh: Introduction to IT programs'+char(10)+N'Số tín chỉ: 2.'+char(10)+N'Tóm tắt nội dung: Môn học cung cấp các kiến thức giới thiệu về ngành CNTT nói chung và các chuyên ngành sâu nói riêng gồm: Khoa học máy tính, Kỹ thuật máy tính, Kỹ thuật phần mềm, Mạng máy tính & truyền thông và Hệ thống thông tin. Trong đó cung cấp cho sinh viên biết trong mỗi ngành sẽ học những gì và ra trường sẽ làm được gì, làm ở đâu.', null)
insert into MON_HOC values (N'Cơ sở dữ liệu',N'Tên tiếng Anh: Fundamental Database'+char(10)+N'Số tín chỉ: 4'+char(10)+N'Tóm tắt nội dung: cung cấp cho sinh viên các kiến thức về cơ sở dữ liệu như: khái niệm cơ bản về cơ sở dữ liệu quan hệ; Các phép toán đại số quan hệ; Ngôn ngữ SQL; Ngôn ngữ tân từ, Các ràng buộc toàn vẹn trên một sở dữ liệu; Quản trị bên trong cơ sở dữ liệu, môi trường khách/chủ.',null)
insert into MON_HOC values (N'Nhập môn lập trình',N'Tên tiếng Anh: Introduction to Programming.'+char(10)+N'Số tín chỉ: 4.'+char(10)+N'Tóm tắt nội dung: Môn học cung cấp cho sinh viên các kiến thức cơ bản về máy tính điện tử, biểu diễn thông tin trong máy tính điện tử; cung cấp sơ lược các kiến thức về hệ điều hành. Đồng thời, giúp sinh viên nắm vững khái niệm giải thuật và các phương pháp thiết kế giải thuật, phương pháp tin học hóa một bài toán. Rèn luyện cho sinh viên kỹ năng lập trình trên nền tảng ngôn ngữ C.',null)
insert into MON_HOC values (N'Những nguyên lý cơ bản của chủ nghĩa Mác – Lênin',N'Tên tiếng Anh: Principles of Marxist and Lennist.'+char(10)+N'Số tín chỉ: 5.'+char(10)+N'Tóm tắt nội dung: Ngoài 1 chương mở đầu nhằm giới thiệu khái lược về chủ nghĩa Mác-Lênin và một số vấn đề chung của môn học. Căn cứ vào mục tiêu môn học, nội dung chương trình môn học được cấu trúc thành 3 phần, 9 chương: Phần thứ nhất có 3 chương bao quát những nội dung cơ bản về thế giới quan và phương pháp luận của chủ nghĩa Mác-Lênin; phần thứ hai có 3 chương trình bày ba nội dung trọng tâm thuộc học thuyết kinh tế của chủ nghĩa Mác-Lênin về phương thức sản xuất tư bản chủ nghĩa; phần thứ ba có 3 chương, trong đó có 2 chương khái quát những nội dung cơ bản thuộc lý luận của chủ nghĩa Mác-Lênin về chủ nghĩa xã hội và 1 chương khái quát chủ nghĩa xã hội hiện thực và triển vọng.',null)
insert into MON_HOC values (N'Đường lối cách mạng của Đảng Cộng sản Việt Nam',N'Tên tiếng Anh: Revolution Lines of Vietnam Communist Party.'+char(10)+N'Số tín chỉ: 3.'+char(10)+N'Tóm tắt nội dung: Ngoài chương mở đầu, nội dung môn học gồm 8 chương: Chương I: Sự ra đời của Đảng Cộng sản Việt Nam và Cương lĩnh chính trị đầu tiên của Đảng; chương II: Đường lối đấu tranh giành chính quyền (1930-1945); chương III: Đường lối kháng chiến chống thực dân Pháp và đế quốc Mỹ xâm lược (1945-1975); chương IV: Đường lối công nghiệp hoá; chương V: Đường lối xây dựng nền kinh tế thị trường định hướng xã hội chủ nghĩa; chương VI: Đường lối xây dựng hệ thống chính trị; chương VII: Đường lối xây dựng văn hoá và giải quyết các vấn đề xã hội; chương VIII: Đường lối đối ngoại.',null)
insert into MON_HOC values (N'Tư tưởng Hồ Chí Minh',N'Tên tiếng Anh: Ho Chi Minh Ideology.'+char(10)+N'Số tín chỉ: 2.'+char(10)+N'Tóm tắt nội dung: Ngoài chương mở đầu, nội dung môn học gồm 7 chương: chương 1, trình bày về cơ sở, quá trình hình thành và phát triển tư tưởng Hồ Chí Minh; từ chương 2 đến chương 7 trình bày những nội dung cơ bản của Tư tưởng Hồ Chí Minh theo mục tiêu môn học.', 'csdl\\IMAGES\\MON_HOC\\TutuongHCM.jpg')
insert into MON_HOC values (N'Giải tích 1',N'Tên tiếng Anh: Analytics 1.'+char(10)+N'Số tín chỉ: 4.'+char(10)+N'Tóm tắt nội dung: Môn học cung cấp các kiến thức nhập môn giải tích. Nội dung bao gồm :'+char(10)+N'- Số phức.'+char(10)+N'- Phép tính vi phân của hàm nhiều biến, công thức Taylor, đạo hàm theo hướng.'+char(10)+N'- Ứng dụng của hàm nhiều biến trong bài toán cực trị, trong hình học.'+char(10)+N'- Phép tính tích phân của hàm một biến.'+char(10)+N'- Chuỗi số, chuỗi hàm.', 'csdl\\IMAGES\\MON_HOC\\Giaitich1.jpg')
insert into MON_HOC values (N'Giải tích 2',N'Tên tiếng Anh: Analytics 2'+char(10)+N'Số tín chỉ: 4'+char(10)+N'Tóm tắt nội dung: Một số nội dung chính của môn học là:'+char(10)+N'- Phép tính tích phân của hàm nhiều biến: tích phân kép, tích phân bội, tích phân đường, tích phân mặt.'+char(10)+N'- Phương trình vi phân cấp một, phương trình vi phân cấp hai, hệ phương trình vi phân.', 'csdl\\IMAGES\\MON_HOC\\Giaitich2.jpg')
insert into MON_HOC values (N'Đại số tuyến tính',N'Tên tiếng Anh: Linear Algebra'+char(10)+N'Số tín chỉ: 4'+char(10)+N'Tóm tắt nội dung: Một số nội dung chính của môn học là:'+char(10)+N'- Ma trận, định thức, hệ phương trình tuyến tính. Giải hệ phương trình tuyến tính bằng phương pháp Cramer, phương pháp Gauss.'+char(10)+N'- Không gian tuyến tính, sự phụ thuộc, độc lập tuyến tính.'+char(10)+N'- Chéo hóa ma trận và ý nghĩa của nó.', 'csdl\\IMAGES\\MON_HOC\\dstt.jpg')
insert into MON_HOC values (N'Nhập môn điện tử',N'Tên tiếng Anh: Basic Electronics'+char(10)+N'Số tín chỉ: 3'+char(10)+N'Tóm tắt nội dung: Trang bị cho sinh viên những kiến thức cơ bản kiến thức về hệ thống điện tử và ứng dụng của chúng trong các hệ thống thiết bị kỹ thuật công nghệ. Nguyên lý cấu trúc và các bài toán cơ bản về quá trình thu thập, xử lý thông tin và ra các quyết định điều khiển.',null)
insert into MON_HOC values (N'Nội dung môn Nhập môn mạch số',N'Tên tiếng Anh: Introduction to Digital Circuits'+char(10)+N'Số tín chỉ: 4'+char(10)+N'Tóm tắt nội dung: Trang bị cho sinh viên những kiến thức về sơ đồ cấu tạo mạch số ở mức cổng logic, giải thích nguyên tắc hoạt động, ứng dụng của các mạch cơ bản dùng để tạo nên các hệ thống điện tử kĩ thuật số, vận dụng các nguyên tắc để thiết kế mạch số đơn giản.',null)
insert into MON_HOC values (N'Xác suất thống kê',N'Tên tiếng Anh: Probability and Statistic'+char(10)+N'Số tín chỉ: 3'+char(10)+N'Tóm tắt nội dung: Trang bị cho sinh viên kiến thức cơ bản về Lý thuyết Xác suất- Thống kê làm nền tảng cho việc xử lý các bài toán liên quan đến hiện tượng và quá trình ngẫu nhiên của một kỹ sư CNTT. Có các kỹ năng tư duy, phân tích và ra quyết định, kỹ năng phát hiện và giải quyết vấn đề, kỹ năng mô hình hóa các bài toán thực tế bằng công thức toán học, có thể tiếp thu được các kiến thức chuyên ngành có sử dụng toán học và biết tính toán, xử lý số liệu trong công tác chuyên môn.', 'csdl\\IMAGES\\MON_HOC\\xstk.jpg')
insert into MON_HOC values (N'Anh Văn',N'Tên tiếng Anh: English'+char(10)+N'Số tín chỉ: 12'+char(10)+N'Tóm tắt nội dung: cung cấp cho sinh viên những kiến thức về anh văn để sinh viên tự tích lũy và phải đạt TOEFL - quốc tế: từ 400 điểm trở lên và TOEFL -trong nước: từ 450 điểm trở lên mới được tốt nghiệp.',null)
insert into MON_HOC values (N'Giáo dục thể chất',N'Tên tiếng Anh: Physical Education'+char(10)+N'Số tín chỉ:'+char(10)+N'Tóm tắt nội dung: Đào tạo theo nội dung ban hành tại Quyết định số 3244/GD&ĐT, ngày 12/09/1995 và Quyết định số1262/GD-ĐT ngày 12/04/1997 của Bộ trưởng Bộ Giáo dục và Đào tạo',null)
insert into MON_HOC values (N'Giáo dục quốc phòng',N'Tên tiếng Anh: Military Education'+char(10)+N'Số tín chỉ:'+char(10)+N'Tóm tắt nội dung: Đào tạo theo nội dung ban hành tại Quyết định số 12/2000/QĐ-BGD&ĐT, ngày 09/05/2000 của Bộ trưởng Bộ Giáo dục và Đào tạo',null)
insert into MON_HOC values (N'Kỹ năng nghề nghiệp',N'Tên tiếng Anh: Professional skills'+char(10)+N'Số tín chỉ: 2'+char(10)+N'Tóm tắt nội dung: Môn học cung cấp các kỹ năng hỗ trợ năng lực chuyên môn và nghề nghiệp trong lĩnh vực CNTT cần thiết cho sinh viên trường Đại học Công nghệ Thông tin. Trên cơ sở phương pháp luận tiếp cận hệ thống, nội dung môn học hướng sinh viên tới việc chủ động thực hiện quá trình học và tự học đại học và tốt nghiệp với phẩm chất đạo đức tốt, có kiến thức và kỹ năng chuyên môn đáp ứng yêu cầu làm việc của xã hội: Kỹ năng đọc, nghe và ghi chép; kỹ năng đối thoại; kỹ năng tự học; kỹ năng làm việc nhóm; kỹ năng quan sát, nhận diện và giải quyết vấn đề; kỹ năng thuyết trình và điều khiển cuộc họp; kỹ năng tổ chức công việc; kỹ năng thực hành nghề nghiệp; kỹ năng soạn thảo văn bản, viết báo cáo.',null)
insert into MON_HOC values (N'Kiến trúc máy tính',N'Tên tiếng Anh: Computer Architecture'+char(10)+N'Số tín chỉ: 3'+char(10)+N'Tóm tắt nội dung: trình bày về kiến trúc máy tính, thiết kế của các máy tính, và là học phần cơ sở cho sinh viên công nghệ thông tin trong một học kỳ. Chương 1 trình bày về lịch sử phát triển, những định hướng phát triển hiện tại và tương lai. Chương 2 giới thiệu sơ lược về nguyên lý hoạt động cũng như các tính chất của các thành phần cơ bản trong máy tính. Chương 3 trình bày về biểu diễn dữ liệu trong máy tính. Chương 4 và 5 trình bày về mạch logic số. Chương 6 tổng hợp các kiến trúc bộ lệnh và chương 7 về tổ chức bộ vi xử lý.', 'csdl\\IMAGES\\MON_HOC\\ktmt.jpg')
insert into MON_HOC values (N'Cấu trúc rời rạc',N'Tên tiếng Anh: Discrete Structure'+char(10)+N'Số tín chỉ: 4'+char(10)+N'Tóm tắt nội dung: Cung cấp cho sinh viên những kiến thức cơ bản về'+char(10)+N'- Toán rời rạc: Cơ sở lôgic; Các phương pháp đếm; Quan hệ; Đại số Bool.'+char(10)+N'- Lý thuyết đồ thị: Các khái niệm cơ bản của lý thuyết đồ thị; Đồ thị và cây.Đồ thị và cây và một số khái niệm cơ bản của lý thuyết đồ thị,.', 'csdl\\IMAGES\\MON_HOC\\ctrr.jpg')
insert into MON_HOC values (N'Cấu trúc dữ liệu và giải thuật',N'Tên tiếng Anh: Data Structures and Algorithms'+char(10)+N'Số tín chỉ: 4'+char(10)+N'Tóm tắt nội dung: Môn học giúp sinh viên hiểu tầm quan trọng của giải thuật và cách tổ chức dữ liệu, là hai thành tố quan trọng nhất cho một chư­ơng trình. Giúp sinh viên nắm bắt, áp dụng các giải thuật, các cấu trúc dữ liệu thường được áp dụng trong việc giải quyết bài toán trong tin học. Ngoài ra, môn học còn giúp sinh viên củng cố và phát triển kỹ năng lập trình vừa đư­ợc học trong môn học trước.',null)
insert into MON_HOC values (N'Hệ điều hành',N'Tên tiếng Anh: Operating Systems'+char(10)+N'Số tín chỉ: 4'+char(10)+N'Tóm tắt nội dung:Giới thiệu các khái niệm đi theo trình tự từ đơn giản đến phức tạp, môn học gồm có 9 chương ứng với cấu trúc máy tính từ đơn giản đến phức tạp. Sáu chương đầu giới thiệu các khái niệm cơ bản của một hệ điều hành. Ba chương sau là phần năng cao.', 'csdl\\IMAGES\\MON_HOC\\hdh.jpg')
insert into MON_HOC values (N'Nhập môn mạng máy tính',N'Tên tiếng Anh: Computer Networks'+char(10)+N'Số tín chỉ : 4'+char(10)+N'Tóm tắt nội dung: cung cấp những khái niệm tổng quan về mạng máy tính, bao gồm mô hình tham chiếu OSI, TCP/IP và các chuẩn mạng; những khái niệm, nguyên lý cơ bản về tín hiệu, truyền tín hiệu. Sinh viên được tìm hiểu sâu về mô hình TCP/IP như các giao thức trong các tầng đặc biệt là tầng mạng và tầng vận chuyển. Ngoài ra sinh viên cũng được làm quen với các dịch vụ mạng cơ bản, kỹ thuật mạng không dây và bảo mật mạng.', 'csdl\\IMAGES\\MON_HOC\\mmt.jpg')
insert into MON_HOC values (N'Lập trình trực quan',N'Tên tiếng Anh: Visual Programming'+char(10)+N'Số tín chỉ: 4'+char(10)+N'Tóm tắt nội dung: Cung cấp cho sinh viên những kiến thức cơ bản về phương pháp lập trình trên môi trường Windows: cơ chế quản lý chương trình, lập trình giao diện đồ họa (GUI), lập trình WPF, GDI+, quản lí tiến trình, đồng bộ hóa…, từ đó sinh viên có khả năng tự xây dựng 1 ứng dụng hoàn chỉnh ở mức độ vừa phải bằng ngôn ngữ C#. Môn học cũng cung cấp cho sinh viên một số kiến thức cơ bản để có thể tự nghiên cứu các kỹ thuật lập trình sâu hơn trên môi trường Windows.',null)
insert into MON_HOC values (N'Giới thiệu ngành',N'Tên tiếng Anh: Introduction to IT programs'+char(10)+N'Số tín chỉ: 2'+char(10)+N'Tóm tắt nội dung: Môn học cung cấp các kiến thức giới thiệu về ngành CNTT nói chung và các chuyên ngành sâu nói riêng gồm: Khoa học máy tính, Kỹ thuật máy tính, Kỹ thuật phần mềm, Mạng máy tính & truyền thông và Hệ thống thông tin. Trong đó cung cấp cho sinh viên biết trong mỗi ngành sẽ học những gì và ra trường sẽ làm được gì, làm ở đâu.',null)
insert into MON_HOC values (N'Nhập môn công tác kỹ sư',N'Tên tiếng Anh: Introduction to Working of Engineer'+char(10)+N'Số tín chỉ: 2'+char(10)+N'Tóm tắt nội dung: Môn học này trình bày về những kỹ năng mềm cần thiết đối với một người kỹ sư trong xã hội hiện nay, được chia thành 6 chương. Chương 1 trình bày về những khái niệm chung liên quan đến công tác kỹ sư. Các chương sau chú trọng đến từng kỹ năng riêng biệt. Chương 2 trình bày về kỹ năng ghi chép. Chương 3 trình bày về kỹ năng đối thoại. Chương 4 trình bày về kỹ năng thuyết trình và điều khiển cuộc họp. Chương 5 trình bày về kỹ năng thực hành nghề nghiệp bao gồm kỹ năng thực tập và thực hiện khóa luận tốt nghiệp. Chương cuối cùng trình bày về kỹ năng soạn thảo văn bản trong xí nghiệp.',null)

--Insert GIANG_VIEN
insert into GIANG_VIEN values (N'Thầy Phạm Thi Vương là ai?',N'Thầy Vương tên đầy đủ là Phạm Thi Vương, phó khoa Công nghệ Phần mềm trường Đại học Công Nghệ Thông Tin.'+char(10)+N'Thầy tham gia giảng dạy các môn Nhập môn lập trình(IT001), Lập trình trực quan(IT008), Lập trình hướng đối tượng(IT002), Phương pháp Phát triển phần mềm hướng đối tượng(SE100), Đặc tả hình thức(SE106),...'+char(10)+N'Email liên lạc: vuongpt@uit.edu.vn', 'csdl\\IMAGES\\GIANG_VIEN\\T.VUONG.png')
insert into GIANG_VIEN values (N'Trưởng khoa Hệ thống thông tin là ai?',N'Trưởng khoa hệ thống thông tin là thầy PGS.TS Nguyễn Đình Thuân.'+char(10)+N'Các hướng nghiên cứu của thầy chủ yếu là Khai phá dữ liệu, Cơ sở dữ liệu, Xử lý số liệu, Thương mại điện tử.'+char(10)+N'Những công trình nghiên cứu và được công bố như:'+char(10)+N'- An Approach to Mining Time Pattern Association Rules in Temporal Database. The 2nd Asia Pacific International Conference on Information Science and Technology (APIC-IST) December,2007,Hanoi,Vietnam.'+char(10)+N'Các dạng chuẩn trong Cơ sở dữ liệu quan hệ có yếu tố thời gian. Kỷ yếu Hội thảo Quốc gia Một số vấn đề chọn lọc của Công nghệ Thông tin-Thái Nguyên. NXB Khoa học Kỹ thuật Hà Nội, 2005, trang 395-402.'+char(10)+N'Email liên lạc: thuannd@uit.edu.vn', 'csdl\\IMAGES\\GIANG_VIEN\\Hethongthongtin\\thuannd.jpg')
insert into GIANG_VIEN values (N'Phó khoa Hệ thống thông tin là ai?',N'Phó khoa hệ thống thông tin là Ths.Nguyễn Thị Kim Phụng.'+char(10)+N'Hướng nghiên cứu chủ yếu: Xử lí ngôn ngữ tự nhiên, Sinh tin học, Khai phá dữ liệu.'+char(10)+N'Những công trình nghiên cứu như: Using spectral vector and M-Tree  for graph clustering and searching in graph databases and protein structures, WASET, ICBCSB 2009: International conference on BioInformatics, Computational and systems biology, Singapore, Aug-2009, ISSN  2070-3724, pp 296-301 là bài báo được cô và Đỗ Phúc nghiên cứu và công bố.'+char(10)+N'Ngoài ra cô cũng cho ra  bài báo Using the Naive Bayes model and natural language processing for classifying the messages on online forum, IEEE RIVF 2007, pp 247-252 vào năm 2010.'+char(10)+N'Email liên lạc: phungntk@uit.edu.vn', 'csdl\\IMAGES\\GIANG_VIEN\\Hethongthongtin\\phungntk.jpg')
insert into GIANG_VIEN values (N'Trưởng khoa Công nghệ phần mềm là ai?',N'Trưởng khoa CNPM là PGS. TS. Vũ Thanh Nguyên. Thầy cũng là trưởng bộ môn MTA&PTG.'+char(10)+N'Quan tâm tìm hiểu: Quy trình và công nghệ sản xuất phần mềm, game'+char(10)+N'Thầy có tham gia giảng dạy một số môn như:'+char(10)+N'Một số thuật toán thông minh - SE313.H21.PMCL, Đặc tả hình thức - SE106.H22.PMCL, Đặc tả hình thức - SE106.H21.PMCL, Phương pháp mô hình hóa - SE101.H12.PMCL, Phương pháp mô hình hóa - SE101.H11.PMCL, Đặc tả hình thức - SE106.G21.PMCL, Đồ án môn học mã nguồn mở - SE111.G11.PMCL, Phương pháp mô hình hóa - SE101.G11.PMCL, Cấu trúc rời rạc - MA004.G12.PMCL, Cấu trúc rời rạc - MA004.G11.PMCL, Đồ án mã nguồn mở - SE111.H21, Serminar các vấn đề hiện đại của CNPM - SE400.H21, Đặc tả hình thức - SE106.H22, Đặc tả hình thức - SE106.H21, Đồ án mã nguồn mở - SE111.H11, Serminar các vấn đề hiện đại của CNPM - SE400.H11, Đặc tả hình thức - SE106.H11, Phương pháp mô hình hóa - SE101.H12, Đặc tả hình thức - SE106.G22, Đặc tả hình thức - SE106.G21, ...'+char(10)+N'Email liên lạc: nguyenvt@uit.edu.vn', 'csdl\\IMAGES\\GIANG_VIEN\\T.NGUYEN.png')
insert into GIANG_VIEN values (N'Phó khoa Công nghệ phần mềm là ai?',N'Phó khoa CNPM là ThS.Phạm Thi Vương.'+char(10)+N'Hướng nghiên cứu: Các phương pháp biểu diễn tri thức, các hệ thống thông minh, hệ hỗ trợ học tập thông minh, suy diễn tự động.'+char(10)+N'Quan tâm tìm hiểu: Quy trình và công nghệ sản xuất phần mềm, game'+char(10)+N'Những môn thầy tham gia giảng dạy:'+char(10)+N'Hướng dẫn sử dụng moodle dành cho sinh viên, Công nghệ .NET - SE310.H21.PMCL, Lập trình trực quan - IT008.H23.CLC, Lập trình trực quan - IT008.H22.CLC, Lập trình trực quan - IT008.H21.CLC, Lập trình hướng đối tượng - IT002.H23.CLC, Lập trình hướng đối tượng - IT002.H22.CLC, Lập trình hướng đối tượng - IT002.H21.CLC, Phương pháp Phát triển phần mềm hướng đối tượng - SE100.H11.PMCL, Nhập môn lập trình - IT001.H11.PMCL, Lập trình hướng đối tượng - IT002.G31.CLC, Lập trình hướng đối tượng - IT002.G21.KHTN, Đặc tả hình thức - SE106.G21.PMCL.1, Đặc tả hình thức - SE106.G21.PMCL, Lập trình hướng đối tượng - IT002.G23.PMCL, Lập trình hướng đối tượng - IT002.G22.PMCL, Lập trình hướng đối tượng - IT002.G21.PMCL, Nhập môn lập trình - IT001.G13.PMCL, Nhập môn lập trình - IT001.G12.PMCL, Nhập môn lập trình - IT001.G11.PMCL, ...'+char(10)+N'Email liên lạc: vuongpt@uit.edu.vn','csdl\\IMAGES\\GIANG_VIEN\\T.VUONG.png')
insert into GIANG_VIEN values (N'Trưởng khoa Mạng máy tính và truyền thông là ai?',N'Trưởng khoa Mạng máy tính và truyền thông là TS. Nguyễn Anh Tuấn'+char(10)+N'Các môn thầy tham gia giảng dạy là:'+char(10)+N'An toàn mạng không dây và di động - NT330.G22.ANTN, An toàn mạng không dây và di động - NT330.G21.ANTN, Hệ điều hành Linux - NT103.G21.ANTN, Nhập môn mạng máy tính - IT005.G11.KHTN, Pháp chứng kỹ thuật số - NT334.G12.ANTN, Nhập môn bảo đảm và an ninh thông tin - IE105.20153.VB2, Lập trình hệ thống - NT209.H22, An toàn mạng không dây và di động - NT330.H21.ANTN, Lập trình Hệ thống, Phương pháp luận nghiên cứu khoa học - CS519.H21.ANTN, An toàn mạng không dây và di động - NT330.H11.ANTT, Lập trình hệ thống - NT209.H11.ANTT, Hệ thống nhúng mạng không dây - NT131.H11.ANTT, Lập trình hệ thống - NT209.H12.ANTN, Lập trình hệ thống - NT209.H11.ANTN, Giới thiệu ngành - IT009.G21, Tính toán lưới - NT333.G21, Lập trình hệ thống và mạng - NT209.G21, Lập trình Hệ thống và Mạng'+char(10)+N'Email liên lạc: tuanna@uit.edu.vn', 'csdl\\IMAGES\\GIANG_VIEN\\Mangmaytinh\\Trkhoa_NguyenAnhTuan.jpg')
insert into GIANG_VIEN values (N'Phó khoa Mạng máy tính và truyền thông là ai?',N'Phó khoa Mạng máy tính và truyền thông là ThS. Tô Nguyễn Nhật Quang '+char(10)+N'Các môn thầy tham gia giảng dạy là:'+char(10)+N'Nhập môn mạng máy tính - IT005.H11.PMCL, Nhập môn mạng máy tính - IT005.H11.HTCL, An toàn mạng máy tính - NT101.G21.ANTN, Nhập môn mạng máy tính - IT005.G11.HTCL, Bảo mật Internet - NT405.H22, Bảo mật Internet - NT405.H21, Mật mã học - NT119.H21.ANTT, An toàn mạng máy tính - NT101.H22, Bảo mật Internet - NT405.H11, Tấn công mạng - NT205.H11, Nhập môn mạng máy tính - IT005.H13, Mật mã học - NT119.G21.ANTT, Thiết bị mạng và truyền thông ĐPT - NT111.G21, Thiết bị mạng và truyền thông ĐPT - NT111.D21'+char(10)+N'Email liên lạc: quangtnn@uit.edu.vn','csdl\\IMAGES\\GIANG_VIEN\\Mangmaytinh\\PhKhoa_ToNguyenNhatQuang.jpg')
insert into GIANG_VIEN values (N'Trưởng khoa Khoa học máy tính là ai?',N'Trưởng khoa Khoa học máy tính là PGS.TS Đỗ Văn Nhơn'+char(10)+N'Môn học giảng dạy:'+char(10)+N'Cấu trúc dữ liệu và giải thuật - IT003.H21.CLC, Nhập môn lập trình - IT001.H12.HTCL, Trí tuệ nhân tạo - CS106.G21.KHTN, Cấu trúc dữ liệu và giải thuật - IT003.G22.MTCL, Cấu trúc dữ liệu và giải thuật - IT003.G22.HTCL, Các hệ cơ sở tri thức - CS217.G11.KHTN, Biểu diễn tri thức và suy luận - CS214.G11.KHTN, Cấu trúc dữ liệu và giải thuật - IT003.H21.CTTN, Các hệ cơ sở tri thức - CS217.H21.KHTN, Trí tuệ nhân tạo - CS106.H21.KHTN, Biểu diễn tri thức và suy luận - CS214.H11.KHTN, Cấu trúc dữ liệu và giải thuật - IT003.G21.KHTN'+char(10)+N'Email liên lạc: nhondv@uit.edu.vn','csdl\\IMAGES\\GIANG_VIEN\\Khoahocmaytinh\\Trkhoa_DoVanNhon.jpg')
insert into GIANG_VIEN values (N'Phó khoa Khoa học máy tính là ai?',N'Phó khoa Khoa học máy tính là Ths. Nguyễn Đình Hiển'+char(10)+N'Môn học giảng dạy:'+char(10)+N'Nhập môn lập trình - IT001.H13.PMCL, Kỹ năng nghề nghiệp - SS004.H12.PMCL, Kỹ năng nghề nghiệp - SS004.H12.MTCL, Cơ sở tính toán - CS3613.G31.CTTT, Lập trình symbolic trong trí tuệ nhân tạo - CS314.G21.KHTN, Kỹ năng nghề nghiệp - SS004.G23.PMCL, Kỹ năng nghề nghiệp - SS004.G22.PMCL, Kỹ năng nghề nghiệp - SS004.G21.PMCL, Nhập môn công nghệ tri thức & máy học - CS110.G11.KHTN, Nhập môn lập trình - IT001.G12.MTCL, Nhập môn lập trình - IT001.G12.HTCL, Toán rời rạc nâng cao - CS521.H11, Mạng neural và thuật giải di truyền - CS410.H11, Biểu diễn tri thức và suy luận - CS214.H11, Nhập môn công nghệ tri thức & máy học - CS110.H12, Nhập môn công nghệ tri thức & máy học - CS110.H11, Nhập môn công nghệ tri thức & máy học - CS110.H11.KHTN, Kỹ năng nghề nghiệp - SS004.H15, Máy học nâng cao - CS315.G31, ...'+char(10)+N'Email liên lạc: hiennd@uit.edu.vn',null)


--Insert THONGTIN_QUYCHE
insert into THONGTIN_QUYCHE(CAUHOI,TRALOI) values (N'Chương trình chất lượng cao đào tạo những ngành nào?',N'Ngoài hệ đại trà, trường đại học còn đào tạo thêm chương trình chất lượng cao và chương trình đặc biệt.'+char(10)+N'Chương trình chất lượng cao trường ĐH CNTT tuyển sinh vào các ngành Hệ thống Thông tin, Kỹ thuật Máy tính, Kỹ thuật Phần mềm.'+char(10)+N'Từ năm 2017 tuyển sinh thêm chương trình chất lượng cao với học phí tương ứng ngành Khoa học Máy tính, Truyền thông và Mạng máy tính.'+char(10)+N'Chương trình được triển khai đào tạo với giáo trình hiện đại, phương pháp giảng dạy bằng song ngữ hoặc toàn bộ bằng tiếng Anh một số môn học.'+char(10)+N'Mức học phí áp dụng cho khóa tuyển 2016 là 28 triệu/năm (2 năm đầu) và 30 triệu/năm (các năm học tiếp theo). Mức học phí này sẽ được điều chỉnh theo từng khóa học theo tỷ lệ tăng học phí phù hợp với quy định hiện hành.')
insert into THONGTIN_QUYCHE(CAUHOI,TRALOI) values (N'Chương trình đào tạo sau đại học ở trường CNTT',N'UIT đào tạo thạc sĩ, tiến sĩ chương trình đào tạo tiên tiến về CNTT. Trường đẩy mạnh hợp tác với các cơ sở nghiên cứu CNTT hàng đầu trong khu vực và thế giới. Hoạt động đào tạo trình độ sau đại học được tổ chức theo hướng gắn kết chặt chẽ với các phòng thí nghiệm và các nhóm nghiên cứu, các chương trình phát triển CNTT-TT, các đề tài, dự án quốc gia, quốc tế và khu vực.'+char(10)+N'Trường ĐH CNTT đào tạo sau đại học 2 nghành Thạc sĩ ngành khoa học máy tính và công nghệ thông tin và Tiến sĩ ngành khoa học máy tính và công nghệ thông tin. Hiện trường đã đào tạo 2 tiến sĩ đầu tiên là: TS. Huỳnh Ngọc Tín và TS. Trương Hải Bằng')
insert into THONGTIN_QUYCHE(CAUHOI,TRALOI) values (N'Tổng quan về ngành Công nghệ phần mềm',N'Mục tiêu đào tạo kỹ sư ngành Kỹ thuật phần mềm có phẩm chất chính trị vững vàng; có kỷ luật, đạo đức nghề nghiệp; nắm vững kiến thức cơ bản và chuyên môn; có khả năng tổ chức thực hiện nhiệm vụ trong phạm vi quyền hạn của một chuyên viên trong lĩnh vực kỹ thuật phần mềm như nắm bắt và phân tích nhu cầu thực tế (phân tích hệ thống, lập kế hoạch, dự án phần mềm, phân tích yêu cầu), phát triển phần mềm (thiết kế phần mềm, lập trình, kiểm thử),…'+char(10)+N'Bên cạnh đó, sinh viên luôn được trau dồi kiến thức chuyên môn, nâng cao tay nghề, đồng thời được liên kết chặt chẽ với nhiều tổ chức, doanh nghiệp liên quan nhằm bám sát thực tế, liên tục cập nhật các chuẩn, công nghệ mới nhất để nâng cao chất lượng, tăng khả năng cạnh tranh và hội nhập, đồng thời đáp ứng một cách tốt nhất nhu cầu ngày càng cao của xã hội. Sinh viên kiến thức tổng quát về quy trình xây dựng, quản lý và bảo trì hệ thống phần mềm; có khả năng phân tích, thiết kế và quản lý các dự án phần mềm; cung cấp phương pháp luận và công nghệ mới để sinh viên có thể nắm bắt và làm chủ các tiến bộ khoa học. Sinh viên được cung cấp kiến thức cơ bản về tổ chức và quản lý công nghệ phần mềm để có khả năng xây dựng mô hình và áp dụng các nguyên tắc của công nghệ phần mềm vào thực tế.'+char(10)+N'Khoa bao gồm 2 bộ môn: Bộ môn Phát triển phần mềm và bộ môn Môi trường ảo và phát triển game.'+char(10)+N'Sinh viên tốt nghiệp sẽ trở thành các kỹ sư phần mềm có chất lượng tốt, có thể làm việc trong các dự án phần mềm vừa và lớn như sau: Các công ty phát triển phần mềm, thiết kế website, gia công phần mềm, game; bộ phận vận hành và phát triển CNTT của các cơ quan, nhà máy, trường học, ngân hàng, …,các doanh nghiệp có ứng dụng CNTT; các trường đại học, cao đẳng, trung học chuyên nghiệp thuộc lĩnh vực CNTT. Chuyên viên phân tích, thiết kế, cài đặt, quản trị, bảo trì các phần mềm máy tính đáp ứng các ứng dụng khác nhau trong các cơ quan, công ty, trường học...Làm việc ở bộ phận công nghệ thông tin hoặc cần ứng dụng công nghệ thông tin của tất cả các đơn vị có nhu cầu (hành chính sự nghiệp, ngân hàng, viễn thông, hàng không, xây dựng…).Làm việc trong các công ty sản xuất, gia công phần mềm trong nước cũng như nước ngoài. Làm việc tại các công ty tư vấn về đề xuất giải pháp, xây dựng và bảo trì các hệ thống thông tin.')
insert into THONGTIN_QUYCHE(CAUHOI,TRALOI) values (N'Tổng quan về ngành Khoa học máy tính',N'Hiện nay, với sự phát triển của ngành CNTT và những định hướng phát triển của đất nước ta đối với ngành CNTT, thì ngành Khoa học máy tính đóng vai trò rất quan trọng trong việc xây dựng các nền tảng nghiên cứu, phát triển các công nghệ trong tương lai, đặc biệt là những nghiên cứu ứng dụng thiết thực trong cuộc sống.'+char(10)+N'Chương trình đào tạo ngành Khoa học máy tính có nhiệm vụ đào tạo ngồn nhân lực chất lượng cao cho ngành CNTT. Sinh viên tốt nghiệp chương trình Cử nhân Khoa học máy tính đáp ứng các yêu cầu sau: Có kiến thức cơ bản và chuyên sâu về khoa học máy tính và công nghệ thông tin, có khả năng thiết kế các hệ thống xử lý tính toán phức tạp, các phần mềm có chất lượng khoa học và công nghệ cao, thử nghiệm, quản lý các hệ thống máy tính, các hệ thống tin học. Có khả năng triển khai xây dựng các hệ thống ứng dụng tin học và phân tích, thiết kế xây dựng các phần mềm có giá trị thực tiễn cao, có tính sáng tạo, đặc biệt là các ứng dụng thông minh dựa trên việc xử lý tri thức, xử lý ngôn ngữ tự nhiên, xử lý và khai thác dữ liệu đa phương tiện. Có khả năng tự học học tập, phân tích độc lập và nghiên cứu các vấn đề chuyên sâu về lĩnh vực Khoa học máy tính và các ứng dụng của khoa học máy tính trong Công nghệ thông tin ; có thể tiếp tục học tập ở bậc đào tạo sau đại học. Có khả năng giải quyết các vấn đề phức tạp trong các tình huống nảy sinh trong quá trình làm việc, phân tích và đề xuất giải pháp phù hợp với thực tế để giải quyết. Có khả năng thiết lập các mục tiêu khả thi, lập kế hoạch phù hợp với điều kiện thực tế để hoàn thành công việc được giao. Có khả năng giao tiếp xã hội, làm việc hợp tác, làm việc nhóm và làm việc trong một tổ chức; có khả năng vận dụng các kiến thức, kỹ năng và kinh nghiệm để giải quyết các tình huống nghề nghiệp khác nhau.')
insert into THONGTIN_QUYCHE(CAUHOI,TRALOI) values (N'Tổng quan về ngành Kỹ thuật máy tính',N'Đây là một ngành học đang được nhà nước ưu tiên phát triển đặc biệt cụ thể qua các chính sách, dự án nhà máy chế tạo chip đầu tiên của Việt Nam đang được triển khai rầm rộ. Theo những khảo sát gần đây thì ngành này đang là một ngành thiếu nhân lực nhất và đặc biệt sẽ thiếu trong vòng 10 năm nữa do các công ty trong ngành này đang chuyển hướng đầu tư vào Việt Nam và do mục tiêu đưa ngành này thành một trong các ngành chủ lực của kinh tế Việt Nam.'+char(10)+N'Nghành Kỹ thuật máy tính (tên tiếng anh Computer Engineering) nhằm nghiên cứu các nguyên lý, phương pháp để thiết kế và phát triển các hệ thống phần cứng và những phần mềm phục vụ cho hoạt động của các thiết bị phần cứng đó. Kỹ thuật máy tính được nói đến trong nhiều khía cạnh của máy tính, từ thiết kế các mạch điện tử đơn giản đến thiết kế vi xử lý, máy tính cá nhân và kể cả các siêu máy tính. Đặc biệt trong việc thiết kế các hệ thống nhúng dùng trong hầu hết các thiết bị điện-điện tử như điện thoại di động, xe hơi, các bộ điều khiển trong các máy móc, các robot công nghiệp.'+char(10)+N'Có thể nói Kỹ thuật máy tính hiện nay có mặt khắp mọi nơi và Kỹ sư kỹ thuật máy tính được đào tạo các kiến thức liên quan đến kỹ thuật điện tử, thiết kế phần mềm, thiết kế phần cứng và tích hợp giữa phần cứng với phần mềm.')
